SLAC/slac-alpha-d9

- composer.lock
just updating composer modules for security
> composer update -W

- web/sites/default/settings.php
- Remove composer-manifest.yml
- [SLACDP22-54] Add initial GitHub actions
- [SLACDP22-54] Update theme directory for linting
- [SLACDP22-54] Change all references of gesso to slac
- [SLACDP22-54] Temporarily disable redis
> [SLACDP22-54] Disable redis for first deployment

- web/themes/slac/source/03-components/card/_card.scss
- web/themes/slac/source/03-components/card/card-event.yml
- web/themes/slac/source/03-components/card/card.stories.jsx
Aside from the virtual event display, which is already configured.
> 78 - event teaser FED (no changes)

- web/themes/slac/source/03-components/card/_card.scss
- web/themes/slac/source/03-components/card/card--small/_card--small.scss
- web/themes/slac/source/03-components/card/card.stories.jsx
- web/themes/slac/source/03-components/card/card.twig
- web/themes/slac/source/03-components/card/card.yml
A few small visual tweaks & the addition of no-image and icon versions.
I think some of the existing card markup & styles can be removed, but I want to get through all the tickets first just in case we end up needing them. Will do a cleanup later.
I wasn't sure how we'd end up handling the button vs cta option; can always revise in integration if it won't be like this.
> 4 - basic card

- web/themes/slac/source/03-components/card/_card.scss
- web/themes/slac/source/03-components/card/card--small/_card--small.scss
- web/themes/slac/source/03-components/card/card-news.yml
- web/themes/slac/source/03-components/card/card.stories.jsx
- web/themes/slac/source/03-components/card/card.twig
- web/themes/slac/source/03-components/card/card.yml
This branches off #45 so I'd recommend merging that one first. This adds styles for the truncated text with gradient as well as the little 'News' tag.
> 56 - news article card

- web/themes/slac/source/03-components/card/_card.scss
- web/themes/slac/source/03-components/card/card--small/_card--small.scss
- web/themes/slac/source/03-components/card/card-news.yml
- web/themes/slac/source/03-components/card/card.stories.jsx
- web/themes/slac/source/03-components/card/card.twig
- web/themes/slac/source/03-components/card/card.yml
These three card PRs build on each other, recommend merging from oldest to newest.
> 79 - news article teaser card

- config/sync/core.base_field_override.node.faq.promote.yml
- config/sync/core.base_field_override.node.faq.title.yml
- config/sync/core.entity_form_display.node.faq.default.yml
- config/sync/core.entity_view_display.node.faq.default.yml
- config/sync/core.entity_view_display.node.faq.teaser.yml
- config/sync/field.field.node.faq.field_answer.yml
- config/sync/field.field.node.faq.field_faq_category.yml
- config/sync/field.storage.node.field_answer.yml
- config/sync/field.storage.node.field_faq_category.yml
- config/sync/language.content_settings.node.faq.yml
- config/sync/node.type.faq.yml
https://forumone.atlassian.net/browse/SLACDP22-104
> SLACDP22-104: create fAQ content type

- web/themes/slac/source/03-components/card/card.stories.jsx
- web/themes/slac/source/03-components/card/card.twig
only one small code change (modifier classes shouldn't be cascading through the card) and some renaming here.
> 32 & 82 - teaser and bio teaser

- composer.json
- composer.lock
- config/splits/local/.htaccess
- config/sync/core.extension.yml
- config/sync/vapn.vapnconfig.yml
Jira: [https://forumone.atlassian.net/browse/SLACDP22-46](https://forumone.atlassian.net/browse/SLACDP22-46)
> SLACDP22-50: Install and min configure View Access Per Node

- config/sync/core.entity_form_display.site_setting_entity.event_default_motif_image.default.yml
- config/sync/core.entity_form_display.site_setting_entity.news_article_default_motif_image.default.yml
- config/sync/core.entity_view_display.site_setting_entity.event_default_motif_image.default.yml
- config/sync/core.entity_view_display.site_setting_entity.news_article_default_motif_image.default.yml
- config/sync/field.field.site_setting_entity.event_default_motif_image.field_motif_image.yml
- config/sync/field.field.site_setting_entity.news_article_default_motif_image.field_motif_image.yml
- config/sync/field.storage.site_setting_entity.field_motif_image.yml
- config/sync/site_settings.site_setting_entity_type.event_default_motif_image.yml
- config/sync/site_settings.site_setting_entity_type.news_article_default_motif_image.yml
https://forumone.atlassian.net/browse/SLACDP22-147
> SLACDP22-147: added site settings

- web/themes/slac/source/03-components/_index.scss
- web/themes/slac/source/03-components/card/card.twig
- web/themes/slac/source/03-components/event-list/_event-list.scss
- web/themes/slac/source/03-components/event-list/event-list.stories.jsx
- web/themes/slac/source/03-components/event-list/event-list.twig
- web/themes/slac/source/03-components/event-list/event-list.yml
https://integration-slac-alpha-d9.pantheonsite.io/themes/slac/storybook/?path=/story/components-event-list--event-list
> 114 - events list

- config/sync/core.entity_view_display.node.news_article.card.yml
- config/sync/core.entity_view_display.node.news_article.teaser.yml
- web/modules/custom/slac_core/src/Plugin/Field/FieldFormatter/TrimmedFirstWysiwygParagraph.php
- web/themes/slac/includes/node.inc
https://forumone.atlassian.net/browse/SLACDP22-159
> SLACDP22-159: check news card for truncated text and flag it as such

- config/sync/core.entity_form_display.paragraph.image_lightbox.default.yml
- config/sync/core.entity_view_display.media.image.image_lightbox.yml
- config/sync/core.entity_view_display.paragraph.image_lightbox.default.yml
- config/sync/core.entity_view_mode.media.image_lightbox.yml
- config/sync/field.field.paragraph.image_lightbox.field_image.yml
- config/sync/paragraphs.paragraphs_type.image_lightbox.yml
https://forumone.atlassian.net/browse/SLACDP22-180
> SLACDP22-180: create image lightbox paragraph and media view mode

- config/sync/core.entity_form_display.paragraph.tab_item.default.yml
- config/sync/core.entity_form_display.paragraph.tabs.default.yml
- config/sync/core.entity_view_display.paragraph.tab_item.default.yml
- config/sync/core.entity_view_display.paragraph.tabs.default.yml
- config/sync/field.field.paragraph.tab_item.field_paragraphs.yml
- config/sync/field.field.paragraph.tab_item.field_tab_heading.yml
- config/sync/field.field.paragraph.tabs.field_tab_paragraphs.yml
- config/sync/field.storage.paragraph.field_tab_heading.yml
- config/sync/field.storage.paragraph.field_tab_paragraphs.yml
- config/sync/paragraphs.paragraphs_type.tab_item.yml
- config/sync/paragraphs.paragraphs_type.tabs.yml
https://forumone.atlassian.net/browse/SLACDP22-178
> SLACDP22-178: create tabs and tab item paragraphs

- config/sync/core.entity_form_display.paragraph.image_lightbox.default.yml
- config/sync/core.entity_form_display.paragraph.media_grid.default.yml
- config/sync/core.entity_view_display.media.image.image_lightbox.yml
- config/sync/core.entity_view_display.paragraph.image_lightbox.default.yml
- config/sync/core.entity_view_display.paragraph.media_grid.default.yml
- config/sync/core.entity_view_mode.media.image_lightbox.yml
- config/sync/field.field.paragraph.image_lightbox.field_image.yml
- config/sync/field.field.paragraph.media_grid.field_media_items.yml
- config/sync/field.storage.paragraph.field_media_items.yml
- config/sync/paragraphs.paragraphs_type.image_lightbox.yml
- config/sync/paragraphs.paragraphs_type.media_grid.yml
https://forumone.atlassian.net/browse/SLACDP22-179
This branch created from branch `SLACDP22-180-bed-image-lightbox` since the paragraph created there is necessary for this feature.
> Slacdp22 179 bed media grid

- config/sync/core.base_field_override.node.blog.promote.yml
- config/sync/core.entity_form_display.node.blog.default.yml
- config/sync/core.entity_view_display.node.blog.default.yml
- config/sync/core.entity_view_display.node.blog.teaser.yml
- config/sync/field.field.node.blog.field_category.yml
- config/sync/field.field.node.blog.field_date.yml
- config/sync/field.field.node.blog.field_dek.yml
- config/sync/field.field.node.blog.field_hero_paragraph.yml
- config/sync/field.field.node.blog.field_link.yml
- config/sync/field.field.node.blog.field_paragraphs.yml
- config/sync/field.field.node.blog.field_series.yml
- config/sync/field.field.node.blog.field_tags.yml
- config/sync/field.field.node.blog.field_teaser.yml
- config/sync/field.field.node.blog.field_teaser_image.yml
- config/sync/field.field.node.blog.field_text.yml
- config/sync/field.storage.node.field_category.yml
- config/sync/field.storage.node.field_series.yml
- config/sync/language.content_settings.node.blog.yml
- config/sync/node.type.blog.yml
https://forumone.atlassian.net/browse/SLACDP22-102
> SLACDP22-102: define blog content type

- config/sync/core.entity_form_display.node.news_article.default.yml
- config/sync/core.entity_view_display.node.news_article.card.yml
- config/sync/core.entity_view_display.node.news_article.default.yml
- config/sync/core.entity_view_display.node.news_article.large_card.yml
- config/sync/core.entity_view_display.node.news_article.reading_text.yml
- config/sync/core.entity_view_display.node.news_article.search_index.yml
- config/sync/core.entity_view_display.node.news_article.teaser.yml
- config/sync/field.field.node.news_article.field_dek.yml
- config/sync/field.storage.node.field_dek.yml
Jira ticket: [https://forumone.atlassian.net/browse/SLACDP22-135](https://forumone.atlassian.net/browse/SLACDP22-135)
I had to run -xOurs to fix merge conflicts on integration.
git merge -Xours SLACDP22-135-news-content-type-update-field-dek
> SLACDP22-135: Change Dek to Long Text

- config/sync/core.entity_form_display.sitewide_alert.sitewide_alert.default.yml
- config/sync/core.entity_view_display.sitewide_alert.sitewide_alert.default.yml
- config/sync/field.field.sitewide_alert.sitewide_alert.field_icon.yml
- config/sync/field.field.sitewide_alert.sitewide_alert.field_kicker.yml
- config/sync/field.storage.sitewide_alert.field_icon.yml
- config/sync/field.storage.sitewide_alert.field_kicker.yml
- config/sync/sitewide_alert.settings.yml
https://forumone.atlassian.net/browse/SLACDP22-189
> SLACDP22-189: update sitewide alert settings

- config/sync/core.entity_form_display.paragraph.table.default.yml
- config/sync/core.entity_view_display.paragraph.table.default.yml
- config/sync/editor.editor.table.yml
- config/sync/field.field.node.landing_page.field_paragraphs.yml
- config/sync/field.field.node.page.field_paragraphs.yml
- config/sync/field.field.paragraph.table.field_table.yml
- config/sync/field.storage.paragraph.field_table.yml
- config/sync/filter.format.table.yml
- config/sync/paragraphs.paragraphs_type.table.yml
- config/sync/user.role.authenticated.yml
https://forumone.atlassian.net/browse/SLACDP22-182
> SLACDP22-182: create table filter and paragraph

- config/sync/core.entity_form_display.paragraph.section_fixed.default.yml
- config/sync/core.entity_view_display.paragraph.section_fixed.default.yml
- config/sync/field.field.paragraph.section_fixed.field_link.yml
- config/sync/field.field.paragraph.section_fixed.field_long_text.yml
- config/sync/field.field.paragraph.section_fixed.field_paragraphs_1.yml
- config/sync/field.field.paragraph.section_fixed.field_paragraphs_2.yml
- config/sync/field.field.paragraph.section_fixed.field_paragraphs_3.yml
- config/sync/field.field.paragraph.section_fixed.field_short_text.yml
- config/sync/field.field.paragraph.section_fixed.field_text.yml
- config/sync/paragraphs.paragraphs_type.section_fixed.yml
https://forumone.atlassian.net/browse/SLACDP22-207
> SLACDP22-207: create fixed column section paragraph

- config/sync/core.entity_view_display.paragraph.section_fixed.default.yml
Needed to change the link output for the heading link. Corresponding PR in the theme repo.
> 208 config export (fixed section)

- config/sync/core.entity_form_display.sitewide_alert.sitewide_alert.default.yml
- config/sync/core.entity_view_display.sitewide_alert.sitewide_alert.default.yml
- config/sync/field.field.sitewide_alert.sitewide_alert.field_alert_message.yml
- config/sync/field.storage.sitewide_alert.field_alert_message.yml
https://forumone.atlassian.net/browse/SLACDP22-95
> SLACDP22-95: remove default message field and replace with custom field

- config/sync/core.entity_view_display.node.news_article.card.yml
- config/sync/field.storage.paragraph.field_text.yml
> 72 - truncate news article cards to match event cards

- composer.patches.json
https://forumone.atlassian.net/browse/SLACDP22-245
> SLACDP22-245: patch environment indicator module

- web/sites/default/settings.php
https://forumone.atlassian.net/browse/SLACDP22-238
> SLACDP22-238: update settings.php with sendgrip key logic

- config/sync/core.extension.yml
- config/sync/metatag.metatag_defaults.403.yml
- config/sync/metatag.metatag_defaults.404.yml
- config/sync/metatag.metatag_defaults.front.yml
- config/sync/metatag.metatag_defaults.global.yml
- config/sync/metatag.metatag_defaults.node.yml
- config/sync/metatag.metatag_defaults.taxonomy_term.yml
- config/sync/metatag.metatag_defaults.user.yml
- config/sync/views.settings.yml
https://forumone.atlassian.net/browse/SLACDP22-223
> SLACDP22-223: configure global metatag settings

- config/sync/core.entity_view_display.node.blog.card.yml
- config/sync/core.entity_view_display.node.blog.teaser.yml
> 126 - show series on blog post cards

- config/sync/core.entity_view_display.node.publication.default.yml
Showing the right fields based on storybook. Seems like we never heard back about adding extra conditional fields so I'm just going off what I see there.
> 125 - config updates for publication detail

- config/sync/core.entity_view_display.node.blog.large_card.yml
Show the "blog post" tag and the series in the kicker.
> 126 - update blog large card display

- .ddev/providers/pantheon.yaml
- config/sync/core.extension.yml
- web/modules/custom/slac_default_content/content/media/50427ebe-4699-4b6f-8dee-adbdc50dd9da.yml
- web/modules/custom/slac_default_content/content/media/8e52d9e1-eb2f-463e-9b7f-7adfef878261.yml
- web/modules/custom/slac_default_content/content/media/9a00b18c-8571-4753-b46e-62cb03c3a52f.yml
- web/modules/custom/slac_default_content/content/media/ac3ff98a-d2c0-4a6b-8093-c92bbad4aaca.yml
- web/modules/custom/slac_default_content/content/media/bf463fba-68fe-4478-91b5-779b68e7b8c8.yml
- web/modules/custom/slac_default_content/content/menu_link_content/1fd7123b-875a-4e03-9c71-33debf36dae2.yml
- web/modules/custom/slac_default_content/content/menu_link_content/234e2d91-0d2b-41ba-936b-a7fe04c140a3.yml
- web/modules/custom/slac_default_content/content/menu_link_content/3a9732c1-0b38-4697-9a4d-b82279df545c.yml
- web/modules/custom/slac_default_content/content/menu_link_content/43a2eade-449b-408b-ac5f-fb199aaf09fd.yml
- web/modules/custom/slac_default_content/content/menu_link_content/44e51240-ce35-4926-b40e-f59b106ca9bc.yml
- web/modules/custom/slac_default_content/content/menu_link_content/44fcf201-524d-4f54-8658-91496a5436d1.yml
- web/modules/custom/slac_default_content/content/menu_link_content/5fb3646c-428b-4fda-91a9-af55148bc66e.yml
- web/modules/custom/slac_default_content/content/menu_link_content/5fd0bf64-09c7-4f63-ac32-b1d57d362b6e.yml
- web/modules/custom/slac_default_content/content/menu_link_content/90b308ef-5bc3-4186-a1ed-36a73304762c.yml
- web/modules/custom/slac_default_content/content/menu_link_content/9776d3e8-190c-4dac-9d88-735457a3f3ea.yml
- web/modules/custom/slac_default_content/content/menu_link_content/a2851be7-25c6-40e4-a6f1-565147d5da68.yml
- web/modules/custom/slac_default_content/content/menu_link_content/b2c90221-c9d8-4bf0-be0c-05b837a169ba.yml
- web/modules/custom/slac_default_content/content/menu_link_content/b9aa427a-d283-4c6c-837b-bd495584f116.yml
- web/modules/custom/slac_default_content/content/menu_link_content/c9a4442b-540f-4ba7-b01f-4853ea9932cc.yml
- web/modules/custom/slac_default_content/content/menu_link_content/e3aaf908-08c5-4865-822f-704439df3a41.yml
- web/modules/custom/slac_default_content/content/menu_link_content/ed7eeaf5-78c1-4276-b70a-8c0912518390.yml
- web/modules/custom/slac_default_content/content/menu_link_content/f71d3b9e-c303-4a83-976e-2fe0d647ca86.yml
- web/modules/custom/slac_default_content/content/node/2d640f1e-bd17-4a61-8c13-dd6522b914fb.yml
- web/modules/custom/slac_default_content/content/node/a3393c37-0f55-48bf-9354-a28f20f4fcbb.yml
- web/modules/custom/slac_default_content/content/node/ceb86a87-5958-4998-843b-f951b986082a.yml
- web/modules/custom/slac_default_content/content/node/d636b713-605f-444f-bb10-d1e5f9adeee0.yml
- web/modules/custom/slac_default_content/content/site_setting_entity/02ed05be-2d81-4a14-bd30-ac3ac0a93060.yml
- web/modules/custom/slac_default_content/slac_default_content.info.yml
https://forumone.atlassian.net/browse/SLACDP22-210
Merging this will enable the `slac_default_content` module and import all the default content.  Be sure none of it exists in the site you are deploying it to, other wise, deploy will fail.
> SLACDP22-210: define all the default content

- config/sync/facets.facet.audience_taxonomy_term_name_events_grid.yml
- config/sync/facets.facet.event_type_taxonomy_term_name_events_grid.yml
It looks like updating it for one view (grid) updated it for the list as well - I confirmed that they were all correct and this is all that got exported.
> update facet label (capitalization)

- composer.json
- composer.lock
- config/sync/core.extension.yml
- web/profiles/custom/slac_profile/config/default/core.extension.yml
https://forumone.atlassian.net/browse/SLACDP22-318
> SLACDP22-318: reinstall animated_gif

- config/sync/core.entity_view_display.node.event.default.yml
- config/sync/core.entity_view_display.node.event.full.yml
- web/profiles/custom/slac_profile/config/optional/core.entity_view_display.node.event.default.yml
- web/profiles/custom/slac_profile/config/optional/core.entity_view_display.node.event.full.yml
https://forumone.atlassian.net/browse/SLACDP22-301
> SLACDP22-301: add location and event url to google cal export

- config/sync/search_api.index.content.yml
- config/sync/views.view.search.yml
- web/modules/custom/slac_core/src/Plugin/Block/ShareThisPageBlock.php
- web/profiles/custom/slac_profile/config/optional/search_api.index.content.yml
- web/profiles/custom/slac_profile/config/optional/views.view.search.yml
- [SLACDP22-262] Index rendered content
- [SLACDP22-328] Remove FAQ detail pages from search results
> Search updates

- config/sync/auto_entitylabel.settings.site_setting_entity.event_maps.yml
- config/sync/user.role.developer.yml
- config/sync/user.role.manager.yml
- config/sync/workbench_access.access_scheme.section.yml
- web/profiles/custom/slac_profile/config/optional/auto_entitylabel.settings.site_setting_entity.event_maps.yml
- web/profiles/custom/slac_profile/config/optional/workbench_access.access_scheme.section.yml
- web/profiles/custom/slac_profile/config/roles/user.role.developer.yml
- web/profiles/custom/slac_profile/config/roles/user.role.manager.yml
- [SLACDP22] Schema updates for autoentitylabel
- [SLACDP22-352] Turn off default editorial group
- [SLACDP22-351] Allow manager and dev to use aggregator
> [SLACDP22] Update permissions
